name: pooulp_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.7+7

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  connectivity_plus: ^2.2.0
  flutter_datetime_picker: ^1.5.1
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    - assets/svgs/

  fonts:
    - family: TypoRound
      fonts:
        - asset: assets/fonts/typo_round/TypoRound-Bold-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Bold.otf
        - asset: assets/fonts/typo_round/TypoRound-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light.otf
        - asset: assets/fonts/typo_round/TypoRound-Regular.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
