name: pooulp_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  connectivity_plus: ^2.2.0
  # flutter_datetime_picker: ^1.5.1 //issue with themeColor, change direct to git repo
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.5 #^6.0.20
  # pull_to_refresh: ^2.0.0
  image_picker: ^0.8.4+11
  image_cropper: ^3.0.0
  http: ^0.13.4
  # flutter_google_places: ^0.3.0
  uuid: ^3.0.6
  google_sign_in: ^5.4.1
  linkedin_login: ^2.2.1
  pdf: ^3.8.0
  printing: ^5.9.0
  # save file
  path_provider: ^2.0.11

  # open pdf document
  open_file: ^3.2.1

  youtube_player_iframe: ^2.3.0 #^3.0.3

  # share intent
  share_plus: ^4.0.10+1
  # firebase_core: ^1.21.0
  # firebase_dynamic_links: ^4.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    - assets/svgs/
    - assets/data/

  fonts:
    - family: TypoRound
      fonts:
        - asset: assets/fonts/typo_round/TypoRound-Bold-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Bold.otf
        - asset: assets/fonts/typo_round/TypoRound-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light.otf
        - asset: assets/fonts/typo_round/TypoRound-Regular.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
