name: pooulp_flutter
description: A new Flutter project.

publish_to: "none"
version: 1.0.17+21

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_spinkit: ^5.1.0
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  # flutter_datetime_picker: ^1.5.1 //issue with themeColor, change direct to git repo
  #  flutter_datetime_picker:
  #    git:
  #      url: https://github.com/Realank/flutter_datetime_picker.git
  #      ref: master
  flutter_datetime_picker_plus: ^2.1.0
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.5 #^6.0.20
  # pull_to_refresh: ^2.0.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  http: ^1.6.0
  # flutter_google_places: ^0.3.0
  uuid: ^4.5.2
  google_sign_in: ^7.2.0
  linkedin_login: ^3.1.3
  pdf: ^3.8.0
  printing: ^5.9.0
  # save file
  path_provider: ^2.0.11

  # open pdf document
  open_file: ^3.2.1

  youtube_player_iframe: ^5.2.0 #^3.0.3

  # share intent
  share_plus: ^12.0.1
  firebase_core: ^3.15.2
  firebase_dynamic_links: ^6.1.10
  flutter_keychain: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/flags/
    - assets/svgs/
    - assets/data/

  fonts:
    - family: TypoRound
      fonts:
        - asset: assets/fonts/typo_round/TypoRound-Bold-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Bold.otf
        - asset: assets/fonts/typo_round/TypoRound-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Light.otf
        - asset: assets/fonts/typo_round/TypoRound-Regular.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin-Italic.otf
        - asset: assets/fonts/typo_round/TypoRound-Thin.otf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
